---
title: "Oral Presentations/ Invited Talks"
description:
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

- Understanding Sleep Disorders via Subjective and Objective Assessments. Guest lecture on Psych 121S Sleep & Consciousness at UCI (Virtual; 2020, Nov)

- Sleep Interventions to Boost Memory. Guest lecture on Psych 121S Sleep & Consciousness at UCI (Virtual; 2020, Nov)

- Vagolytic effect of Zolpidem on Sleep-dependent Memory: A Trade-off between Working Memory and Long-term Memory. Speaker at the 2020 Neuromatch conference 3.0 (Virtual; 2020, Oct)

- Unsupervised Learning of Sleep Stages from Polysomnography (PSG) Data. 2nd Annual Computational Data Neuroscience Symposium (Virtual; 2020, Oct)

- Age-related Losses in Cardiac Autonomic Activity during a Daytime Nap. 2nd Annual Computational Data Neuroscience Symposium (Virtual; 2020, Oct)

- Spindles switch the sleeping brain from frontal lobe to hippocampal processing: a pharmacology study. Speaker at UCI CogSci Colloquium Flash Talks Series (Virtual; 2020, Oct)

- Coupling of Autonomic and Central events during Sleep Boosts Working Memory in Healthy Young Adults. Speaker at the 2020 Virtual Working Memory Symposium (Virtual; 2020, Aug)

- Cued memory reactivation during sleep influences skill learning. Guest lecture on Psych 129 Sleep & Memory at UCI (Virtual; 2020, May)

- Autonomic-central couplings during Sleep Drives Sleep-dependent Working Memory Gains. Cognitive Science Advancement Talk at UCI (Virtual; 2020, May)

- Autonomic-central couplings during Sleep Drives Sleep-dependent Working Memory Gains. Cognitive Science 3rd-year Talk at UCI, Irvine (2020, May)

- Age-related Sleep and Cognitive Declines: Sleep Disorders and Etiology. Guest lecture on Psych 121S Sleep & Consciousness at UCI (2019, Nov)

- The Roles of Autonomic Activities during Sleep on Cognition. Speaker at the Spring Conference at UCI Center for the Neurobiology of Learning and Memory (2019, May)

- Enhancing Working Memory by Closed-loop tACS during NREM Sleep. Concentration Talk at UCI (2019, Feb)

- Why Do We Sleep? The Impacts of Sleep on Emotion and Memory. Guest speaker at Academic Salon at Taiwanese Graduate Student Association at UCI (2017, Dec)
