---
title: "Teaching Experience"
description:
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Division in Teaching Excellence and Innovation (DTEI), UC Irvine
#### DTEI Graduate Fellow, 2020-2021
Psych Fundamentals, Summer 2020, with Dr. Megan Peters & Dr. Mike D’Zmura

### Department of Statistics, UC Irvine                                       
#### Lab Instructor/ Teaching Assistant
[Basic Statistics](http://catalogue.uci.edu/allcourses/stats/), Winter 2020, with Dr. Lee Kucera

[Introduction to Biostatistics](http://catalogue.uci.edu/allcourses/stats/), Spring 2020, with Dr. Brigitte Baldi

### Department of Cognitive Science, UC Irvine                           
#### Guest Lecturer
[Psychology of Sleep & Consciousness](http://catalogue.uci.edu/allcourses/psych/), Fall 2019, 2020

Sleep & Memory Topics, Spring 2020

Sleep & Consciousness, Fall 2019

#### Lab Instructor/ Teaching Assistant
[Advanced Experimental Psychology](http://catalogue.uci.edu/allcourses/psych/), Winter 2019, with Dr. Aaron Bornstein

[Computer-Based Research in Social Science](http://catalogue.uci.edu/allcourses/soc_sci/), Fall 2018, with Dr. Paul Shirey

[Language and the Brain](http://catalogue.uci.edu/allcourses/psych/), Spring 2019, with Dr. Greg Hickok

[Psych Fundamentals](http://catalogue.uci.edu/allcourses/psych/), Summer 2019, with Dr. Alex Bower

Psychology of Sleep & Consciousness, Fall 2019, with Dr. Sara Mednick

### Department of Psychology, National Chengchi University
#### Lab Instructor/ Teaching Assistant
Introduction to Eye Movements and Cognition, Spring 2016, with Dr. Jie-Li Tsai
